import type {
  CriticalRouteDefinition,
  CriticalWorkflowDefinition,
  DeliveryGate,
  ExecutionPhase,
  PlatformManifest,
  PlatformModule,
  PlatformOwner,
  PlatformSurface,
  RuntimeConfig,
  ServiceDependencyDefinition,
} from "@contentco-op/types";

const PLATFORM_VERSION = "2026.03.phase-1";

function owner(
  group: PlatformOwner["group"],
  role: string,
  productionHealthOwner = role,
  deployOwner = role,
  incidentResponder = role,
): PlatformOwner {
  return {
    group,
    role,
    productionHealthOwner,
    deployOwner,
    incidentResponder,
  };
}

const runtime: RuntimeConfig = {
  required: [
    {
      key: "NEXT_PUBLIC_SUPABASE_URL",
      acceptedAliases: ["SUPABASE_URL"],
      level: "required",
      description: "Shared Supabase project URL for public and authenticated surfaces.",
      appliesTo: ["home", "coscript", "codeliver"],
    },
    {
      key: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
      level: "required",
      description: "Client-safe Supabase anonymous key used by browser sessions.",
      appliesTo: ["home", "coscript", "codeliver"],
    },
    {
      key: "SUPABASE_SERVICE_KEY",
      level: "required",
      description: "Server-side Supabase service role key for platform mutations and automations.",
      appliesTo: ["home", "orchestrator", "documents"],
    },
    {
      key: "CCO_SESSION_SECRET",
      level: "required",
      description: "Session signing secret for authenticated control-plane and portal flows.",
      appliesTo: ["home"],
    },
  ],
  optional: [
    {
      key: "CCO_HOME_URL",
      level: "optional",
      description: "Canonical public base URL for the unified platform shell.",
      devDefault: "http://localhost:4100",
      appliesTo: ["home"],
    },
    {
      key: "CCO_COCUT_URL",
      acceptedAliases: ["CCO_COEDIT_URL"],
      level: "optional",
      description: "Co-Cut product URL used for cross-product navigation and launch targets.",
      devDefault: "http://localhost:5173",
      appliesTo: ["home", "cocut"],
    },
    {
      key: "CCO_COSCRIPT_URL",
      level: "optional",
      description: "Co-Script product URL used for shared navigation and handoffs.",
      devDefault: "http://localhost:4102",
      appliesTo: ["home", "coscript"],
    },
    {
      key: "CCO_CODELIVER_URL",
      level: "optional",
      description: "Co-Deliver product URL used for shared navigation and review handoffs.",
      devDefault: "http://localhost:4103",
      appliesTo: ["home", "codeliver"],
    },
    {
      key: "BLAZE_API_URL",
      acceptedAliases: ["BLAZE_API_BASE_URL"],
      level: "optional",
      description: "Internal operations API endpoint used by the home control plane.",
      appliesTo: ["home"],
    },
    {
      key: "DEER_API_BASE_URL",
      level: "optional",
      description: "Optional analytics/integrity dependency for operator workflows.",
      appliesTo: ["home"],
    },
    {
      key: "DEER_HEALTH_URL",
      level: "optional",
      description: "Health endpoint for external integrity/analytics checks.",
      appliesTo: ["home"],
    },
    {
      key: "ALLOW_PRIVATE_RUNTIME_TARGETS",
      level: "optional",
      description: "Local-development escape hatch for private dependency probing.",
      appliesTo: ["home"],
    },
    {
      key: "OPENAI_API_KEY",
      level: "optional",
      description: "AI provider key for assistant, orchestration, and content automations.",
      appliesTo: ["home", "orchestrator"],
    },
    {
      key: "ANTHROPIC_API_KEY",
      level: "optional",
      description: "Optional secondary model provider for site assistant workflows.",
      appliesTo: ["home"],
    },
    {
      key: "NEXT_PUBLIC_CHATBOT_SCRIPT_URL",
      level: "optional",
      description: "Optional customer-service chatbot loader for the public site shell.",
      appliesTo: ["home"],
    },
    {
      key: "NEXT_PUBLIC_CHATBOT_SITE_KEY",
      level: "optional",
      description: "Optional public site key passed to the chatbot loader.",
      appliesTo: ["home"],
    },
    {
      key: "YOUTUBE_API_KEY",
      level: "optional",
      description: "Optional social and media metadata integration.",
      appliesTo: ["home", "orchestrator"],
    },
    {
      key: "APIFY_TOKEN",
      level: "optional",
      description: "Optional automation provider credential for intake and research automations.",
      appliesTo: ["home", "orchestrator"],
    },
    {
      key: "APIFY_TIKTOK_ACTOR_ID",
      level: "optional",
      description: "Optional actor identifier for TikTok automation routines.",
      appliesTo: ["orchestrator"],
    },
    {
      key: "ORCHESTRATOR_PORT",
      level: "optional",
      description: "Local service port for the orchestration engine.",
      devDefault: "4300",
      appliesTo: ["orchestrator"],
    },
  ],
  localBootNotes: [
    "The monorepo root .env.local.example is the canonical environment template.",
    "apps/home/scripts/verify-runtime-env.mjs blocks runtime startup when required home env vars are missing.",
    "Cross-product URLs are optional in local development but should be set for navigation and smoke-test parity.",
  ],
  productionExpectations: [
    "Public and authenticated Next apps share one canonical Supabase project and session contract.",
    "Control-plane integrations must degrade visibly instead of failing silently when optional env vars are missing.",
    "All production environments should publish health endpoints for app and service readiness.",
  ],
  failureModes: [
    {
      when: "required public Supabase configuration is missing during build",
      behavior: "Build proceeds with warnings so non-sensitive static work can still compile, but runtime checks remain degraded.",
    },
    {
      when: "required runtime env vars for home are missing at startup",
      behavior: "Startup is blocked by verify-runtime-env to prevent half-configured control-plane behavior.",
    },
    {
      when: "optional downstream integrations are missing",
      behavior: "The platform remains online but health surfaces report degraded or missing integrations.",
    },
  ],
};

const dependencies: ServiceDependencyDefinition[] = [
  {
    id: "supabase-core",
    label: "Supabase Core",
    kind: "database",
    required: true,
    usedBy: ["home", "coscript", "codeliver", "orchestrator", "documents"],
    notes: "Primary data, auth, and storage backbone for the unified platform.",
  },
  {
    id: "supabase-storage",
    label: "Supabase Storage",
    kind: "storage",
    required: true,
    usedBy: ["home", "codeliver", "cocut"],
    notes: "Media assets, proof files, and delivery attachments.",
  },
  {
    id: "blaze-api",
    label: "Blaze Internal API",
    kind: "http",
    required: false,
    usedBy: ["home"],
    notes: "Supports internal control-plane and operations surfaces while the full platform converges.",
  },
  {
    id: "stripe",
    label: "Stripe",
    kind: "payments",
    required: false,
    usedBy: ["home"],
    notes: "Quote, invoice, and payment lifecycle integration.",
  },
  {
    id: "orchestrator-engine",
    label: "Orchestrator Engine",
    kind: "queue",
    required: true,
    usedBy: ["home", "orchestrator"],
    notes: "Central workflow execution layer for handoffs, automations, and retries.",
  },
];

const surfaces: PlatformSurface[] = [
  {
    id: "home",
    label: "Platform Shell",
    class: "public_acquisition",
    kind: "app",
    workspace: "apps/home",
    packageName: "@contentco-op/home",
    port: 4100,
    basePath: "/",
    publicUrl: "https://contentco-op.com",
    sourceOfTruth: true,
    description: "Canonical public shell plus internal control-plane entry for the unified Content Co-op platform.",
    healthEndpoint: "/api/health",
    proxyEntryPoint: "apps/home/proxy.ts",
    owner: owner("public_funnel", "platform-shell-owner", "platform-ops", "platform-shell-owner", "platform-ops"),
    modules: [
      "public-homepage",
      "portfolio",
      "booking",
      "brief-intake",
      "client-portal",
      "control-plane",
      "finance-ops",
      "marketing-ops",
      "system-health",
    ],
    requiredServices: ["supabase-core", "supabase-storage", "orchestrator-engine"],
    monitoringTags: ["platform", "home", "control-plane", "public-funnel"],
  },
  {
    id: "cocut",
    label: "Co-Cut",
    class: "domain_product",
    kind: "app",
    workspace: "apps/cocut",
    packageName: "co-cut",
    port: 5173,
    publicUrl: "https://cut.contentco-op.com",
    sourceOfTruth: true,
    description: "Post-production workspace for transcript-first editorial review and collaboration.",
    owner: owner("media_assets", "cocut-product-owner", "media-ops", "cocut-product-owner", "media-ops"),
    modules: ["editorial-review"],
    requiredServices: ["supabase-core", "supabase-storage"],
    monitoringTags: ["product", "cocut", "editorial"],
  },
  {
    id: "coscript",
    label: "Co-Script",
    class: "domain_product",
    kind: "app",
    workspace: "apps/coscript",
    packageName: "co-script",
    port: 4102,
    publicUrl: "https://script.contentco-op.com",
    sourceOfTruth: true,
    description: "Pre-production workspace for briefs, script structure, and development workflows.",
    owner: owner("workflow_orchestration", "coscript-product-owner", "workflow-ops", "coscript-product-owner", "workflow-ops"),
    modules: ["script-development"],
    requiredServices: ["supabase-core", "orchestrator-engine"],
    monitoringTags: ["product", "coscript", "pre-production"],
  },
  {
    id: "codeliver",
    label: "Co-Deliver",
    class: "client_reviewer",
    kind: "app",
    workspace: "apps/codeliver",
    packageName: "co-deliver",
    port: 4103,
    publicUrl: "https://deliver.contentco-op.com",
    sourceOfTruth: true,
    description: "Client and reviewer delivery surface for approvals, comments, and handoff workflows.",
    owner: owner("client_reviewer", "codeliver-product-owner", "client-success-ops", "codeliver-product-owner", "client-success-ops"),
    modules: ["delivery-review", "external-review"],
    requiredServices: ["supabase-core", "supabase-storage", "orchestrator-engine"],
    monitoringTags: ["product", "codeliver", "review", "delivery"],
  },
  {
    id: "orchestrator",
    label: "Orchestrator",
    class: "platform_service",
    kind: "service",
    workspace: "services/orchestrator",
    packageName: "@contentco-op/orchestrator",
    port: 4300,
    sourceOfTruth: true,
    description: "Workflow brain for intake routing, handoffs, and automation supervision.",
    owner: owner("workflow_orchestration", "orchestration-owner", "platform-ops", "orchestration-owner", "platform-ops"),
    modules: ["workflow-engine"],
    requiredServices: ["supabase-core"],
    monitoringTags: ["service", "orchestrator", "workflow"],
  },
  {
    id: "media-worker",
    label: "Media Worker",
    class: "platform_service",
    kind: "worker",
    workspace: "services/media-worker",
    packageName: "@contentco-op/media-worker",
    sourceOfTruth: true,
    description: "Transcoding and media-processing worker for assets and public media.",
    owner: owner("media_assets", "media-worker-owner", "media-ops", "media-worker-owner", "media-ops"),
    modules: ["media-processing"],
    requiredServices: ["supabase-storage"],
    monitoringTags: ["worker", "media", "transcoding"],
  },
  {
    id: "documents",
    label: "Document Renderer",
    class: "platform_service",
    kind: "service",
    workspace: "services/documents",
    packageName: "@contentco-op/documents",
    sourceOfTruth: true,
    description: "Document generation layer for quote, agreement, and invoice output.",
    owner: owner("finance_commercial", "documents-owner", "finance-ops", "documents-owner", "finance-ops"),
    modules: ["document-rendering"],
    requiredServices: ["supabase-core"],
    monitoringTags: ["service", "documents", "finance"],
  },
];

const modules: PlatformModule[] = [
  {
    id: "public-homepage",
    label: "Public Homepage",
    surfaceId: "home",
    businessPurpose: "Top-of-funnel positioning and routing into portfolio, the canonical brief, the booking redirect, and login flows.",
    href: "/",
    owner: owner("public_funnel", "brand-experience-owner"),
    upstreamDependencies: [],
    downstreamDependencies: ["portfolio", "booking", "brief-intake"],
    criticality: "high",
    monitoringTags: ["homepage", "funnel"],
  },
  {
    id: "portfolio",
    label: "Portfolio",
    surfaceId: "home",
    businessPurpose: "Evidence and proof surface for prospects and customer trust-building.",
    href: "/portfolio",
    owner: owner("public_funnel", "brand-experience-owner"),
    upstreamDependencies: ["media-processing"],
    downstreamDependencies: ["booking", "brief-intake"],
    criticality: "high",
    monitoringTags: ["portfolio", "proof"],
  },
  {
    id: "booking",
    label: "Booking",
    surfaceId: "home",
    businessPurpose: "Compatibility redirect into the external Google Meetings booking path for commercial intake.",
    href: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ3V2sQevdtlybFNEhEe3DQ5gE4GNdwNlH-47cIn5iFy0eUY7qxfraJnlq0c7iVoqjGbjhso2ZHl?gv=true",
    owner: owner("finance_commercial", "commercial-ops-owner"),
    upstreamDependencies: ["orchestrator-engine"],
    downstreamDependencies: ["workflow-engine"],
    criticality: "critical",
    monitoringTags: ["booking", "intake"],
  },
  {
    id: "brief-intake",
    label: "Brief Intake",
    surfaceId: "home",
    businessPurpose: "Structured lead and project intake feeding quotes, project creation, and orchestration.",
    href: "/brief",
    owner: owner("workflow_orchestration", "intake-owner"),
    upstreamDependencies: ["supabase-core"],
    downstreamDependencies: ["workflow-engine", "finance-ops"],
    criticality: "critical",
    monitoringTags: ["brief", "intake"],
  },
  {
    id: "client-portal",
    label: "Client Portal",
    surfaceId: "home",
    businessPurpose: "Authenticated client entry into delivery, messaging, and project state.",
    href: "/portal",
    owner: owner("client_reviewer", "client-portal-owner"),
    upstreamDependencies: ["supabase-core"],
    downstreamDependencies: ["delivery-review", "external-review"],
    criticality: "critical",
    monitoringTags: ["portal", "client"],
  },
  {
    id: "control-plane",
    label: "Control Plane",
    surfaceId: "home",
    businessPurpose: "Internal root overview, operations, quotes, contacts, and intervention surfaces.",
    href: "/root/overview",
    owner: owner("platform_reliability", "control-plane-owner"),
    upstreamDependencies: ["supabase-core", "blaze-api"],
    downstreamDependencies: ["finance-ops", "marketing-ops", "system-health"],
    criticality: "critical",
    monitoringTags: ["root", "ops"],
  },
  {
    id: "finance-ops",
    label: "Finance Ops",
    surfaceId: "home",
    businessPurpose: "Quotes, invoices, payments, tax, reconciliation, and commercial controls.",
    href: "/root/finance",
    owner: owner("finance_commercial", "finance-owner"),
    upstreamDependencies: ["supabase-core", "stripe"],
    downstreamDependencies: ["document-rendering"],
    criticality: "critical",
    monitoringTags: ["finance", "billing"],
  },
  {
    id: "marketing-ops",
    label: "Marketing Ops",
    surfaceId: "home",
    businessPurpose: "Campaign, content, and public-surface operations.",
    href: "/root/marketing",
    owner: owner("public_funnel", "marketing-ops-owner"),
    upstreamDependencies: ["supabase-core"],
    downstreamDependencies: ["public-homepage", "portfolio"],
    criticality: "high",
    monitoringTags: ["marketing", "campaigns"],
  },
  {
    id: "system-health",
    label: "System Health",
    surfaceId: "home",
    businessPurpose: "Operational truth for runtime checks, dependencies, and incident-oriented diagnostics.",
    href: "/root/system",
    owner: owner("platform_reliability", "platform-ops"),
    upstreamDependencies: ["supabase-core", "orchestrator-engine", "blaze-api"],
    downstreamDependencies: [],
    criticality: "critical",
    monitoringTags: ["health", "system"],
  },
  {
    id: "editorial-review",
    label: "Editorial Review",
    surfaceId: "cocut",
    businessPurpose: "Editor-facing asset review and cut workflows.",
    owner: owner("media_assets", "cocut-product-owner"),
    upstreamDependencies: ["supabase-storage"],
    downstreamDependencies: ["delivery-review"],
    criticality: "high",
    monitoringTags: ["editing", "review"],
  },
  {
    id: "script-development",
    label: "Script Development",
    surfaceId: "coscript",
    businessPurpose: "Script creation, revision, and planning workflows upstream of production.",
    owner: owner("workflow_orchestration", "coscript-product-owner"),
    upstreamDependencies: ["brief-intake"],
    downstreamDependencies: ["editorial-review"],
    criticality: "high",
    monitoringTags: ["script", "planning"],
  },
  {
    id: "delivery-review",
    label: "Delivery Review",
    surfaceId: "codeliver",
    businessPurpose: "Client-facing approval, asset review, and delivery coordination.",
    owner: owner("client_reviewer", "codeliver-product-owner"),
    upstreamDependencies: ["editorial-review", "supabase-storage"],
    downstreamDependencies: ["external-review"],
    criticality: "critical",
    monitoringTags: ["delivery", "approval"],
  },
  {
    id: "external-review",
    label: "External Review",
    surfaceId: "codeliver",
    businessPurpose: "Token-based reviewer access for fast external feedback without full internal access.",
    owner: owner("client_reviewer", "codeliver-product-owner"),
    upstreamDependencies: ["delivery-review"],
    downstreamDependencies: [],
    criticality: "high",
    monitoringTags: ["review", "external"],
  },
  {
    id: "workflow-engine",
    label: "Workflow Engine",
    surfaceId: "orchestrator",
    businessPurpose: "Queueing, dedupe, routing, retries, and automation supervision for cross-surface workflows.",
    owner: owner("workflow_orchestration", "orchestration-owner"),
    upstreamDependencies: ["brief-intake", "booking", "finance-ops"],
    downstreamDependencies: ["delivery-review", "marketing-ops"],
    criticality: "critical",
    monitoringTags: ["workflow", "queue"],
  },
  {
    id: "media-processing",
    label: "Media Processing",
    surfaceId: "media-worker",
    businessPurpose: "Transcoding, thumbnails, proofs, and derivative media generation.",
    owner: owner("media_assets", "media-worker-owner"),
    upstreamDependencies: ["supabase-storage"],
    downstreamDependencies: ["portfolio", "delivery-review"],
    criticality: "high",
    monitoringTags: ["media", "processing"],
  },
  {
    id: "document-rendering",
    label: "Document Rendering",
    surfaceId: "documents",
    businessPurpose: "Quote, agreement, and invoice rendering for commercial workflows.",
    owner: owner("finance_commercial", "documents-owner"),
    upstreamDependencies: ["finance-ops"],
    downstreamDependencies: [],
    criticality: "high",
    monitoringTags: ["documents", "pdf"],
  },
];

const criticalRoutes: CriticalRouteDefinition[] = [
  {
    id: "public-home",
    path: "/",
    surfaceId: "home",
    accessibility: "public",
    purpose: "Primary acquisition entrypoint.",
    ownerGroup: "public_funnel",
    tags: ["smoke", "public"],
  },
  {
    id: "portfolio",
    path: "/portfolio",
    surfaceId: "home",
    accessibility: "public",
    purpose: "Proof and portfolio showcase.",
    ownerGroup: "public_funnel",
    tags: ["smoke", "portfolio"],
  },
  {
    id: "booking",
    path: "/book",
    surfaceId: "home",
    accessibility: "public",
    purpose: "Compatibility redirect into the Google Meetings booking path; not a standalone intake experience.",
    ownerGroup: "finance_commercial",
    tags: ["smoke", "intake"],
  },
  {
    id: "brief",
    path: "/brief",
    surfaceId: "home",
    accessibility: "public",
    purpose: "Canonical structured creative brief intake.",
    ownerGroup: "workflow_orchestration",
    tags: ["smoke", "intake"],
  },
  {
    id: "health-api",
    path: "/api/health",
    surfaceId: "home",
    accessibility: "internal",
    purpose: "Canonical repo health and runtime readiness endpoint.",
    ownerGroup: "platform_reliability",
    tags: ["health", "api"],
  },
  {
    id: "manifest-api",
    path: "/api/platform/manifest",
    surfaceId: "home",
    accessibility: "internal",
    purpose: "Machine-readable platform topology and runtime contract.",
    ownerGroup: "platform_reliability",
    tags: ["manifest", "api"],
  },
  {
    id: "root-overview",
    path: "/root/overview",
    surfaceId: "home",
    accessibility: "authenticated",
    purpose: "Internal operator landing surface.",
    ownerGroup: "platform_reliability",
    tags: ["ops", "control-plane"],
  },
  {
    id: "root-finance",
    path: "/root/finance",
    surfaceId: "home",
    accessibility: "authenticated",
    purpose: "Finance control plane.",
    ownerGroup: "finance_commercial",
    tags: ["finance", "control-plane"],
  },
];

const criticalWorkflows: CriticalWorkflowDefinition[] = [
  {
    id: "brief-to-quote",
    label: "Brief To Quote",
    ownerGroup: "workflow_orchestration",
    systems: ["home", "orchestrator", "documents"],
    entrypoints: ["/brief", "/api/briefs", "/api/root/briefs/[id]/convert"],
    successSignal: "A submitted brief is visible to operators with a quote-ready state or explicit blockers.",
  },
  {
    id: "quote-to-invoice",
    label: "Quote To Invoice",
    ownerGroup: "finance_commercial",
    systems: ["home", "documents", "stripe"],
    entrypoints: ["/api/root/quotes", "/api/root/invoices", "/api/webhooks/stripe"],
    successSignal: "Commercial records stay linked from quote creation through invoice issuance and payment updates.",
  },
  {
    id: "asset-review-delivery",
    label: "Asset Review Delivery",
    ownerGroup: "client_reviewer",
    systems: ["cocut", "codeliver", "supabase-storage"],
    entrypoints: ["/root/co-edit", "/review/[token]"],
    successSignal: "Assets move from internal review to client/reviewer approval with traceable status changes.",
  },
];

const executionPhases: ExecutionPhase[] = [
  {
    id: "phase-1",
    label: "Platform Convergence",
    objective: "Establish one canonical repo root, topology contract, runtime contract, and deployment model.",
    duration: "Month 1",
    owners: ["public_funnel", "platform_reliability", "workflow_orchestration"],
    scope: [
      "Platform manifest and source-of-truth docs",
      "Canonical environment template",
      "Legacy repo maintenance-only policy",
      "Initial release verification and smoke targets",
    ],
    milestones: [
      {
        id: "p1-m1",
        label: "Source Of Truth Reset",
        targetWindow: "Week 1",
        outcome: "Monorepo, docs, and env policy all agree on the same platform root.",
        dependencies: [],
        exitCriteria: [
          "README and architecture docs describe one canonical platform root",
          "Legacy repos are marked maintenance-only",
          "Shared manifest exists and is machine-readable",
        ],
      },
      {
        id: "p1-m2",
        label: "Runtime Contract Locked",
        targetWindow: "Week 2",
        outcome: "Required and optional env policy is explicit and enforceable.",
        dependencies: ["p1-m1"],
        exitCriteria: [
          "Root env template reflects runtime contract",
          "Startup verification blocks half-configured home runtime",
          "Critical routes and health endpoints are enumerated",
        ],
      },
    ],
    risks: [
      "Teams continue making primary changes in sibling repos",
      "Runtime config remains app-local and drifts again",
    ],
  },
  {
    id: "phase-2",
    label: "Identity And Access",
    objective: "Unify auth, permissions, tenant boundaries, and auditability across platform surfaces.",
    duration: "Month 2",
    owners: ["identity_access", "client_reviewer", "finance_commercial"],
    scope: [
      "Shared role and permission framework",
      "Tenant-aware access boundaries",
      "Audit events for privileged actions",
      "Shared route guard policy",
    ],
    milestones: [
      {
        id: "p2-m1",
        label: "Role Matrix",
        targetWindow: "Week 5",
        outcome: "All protected routes and mutations map to explicit permissions.",
        dependencies: ["p1-m2"],
        exitCriteria: [
          "Role model defined and checked into repo",
          "Protected routes classified by access level",
          "Finance and reviewer boundaries are explicit",
        ],
      },
      {
        id: "p2-m2",
        label: "Audit Spine",
        targetWindow: "Week 8",
        outcome: "Privileged actions produce structured, queryable audit records.",
        dependencies: ["p2-m1"],
        exitCriteria: [
          "Privileged route handlers emit audit events",
          "Role changes and invite flows are logged",
          "Impersonation policy is documented or explicitly deferred",
        ],
      },
    ],
    risks: [
      "App-local auth shortcuts bypass platform rules",
      "Reviewer and client access models diverge across products",
    ],
  },
  {
    id: "phase-3",
    label: "Workflow Backbone",
    objective: "Centralize business flow into one observable orchestration and event model.",
    duration: "Months 3-4",
    owners: ["workflow_orchestration", "finance_commercial", "client_reviewer"],
    scope: [
      "Canonical operational entity model",
      "Platform events and idempotency contracts",
      "Retry, replay, dead-letter, and intervention flows",
      "Operator workflow visibility",
    ],
    milestones: [
      {
        id: "p3-m1",
        label: "Operational Model",
        targetWindow: "Week 10",
        outcome: "Intakes, projects, assets, invoices, and approvals have canonical cross-platform representations.",
        dependencies: ["p2-m2"],
        exitCriteria: [
          "Shared event vocabulary exists",
          "Duplicate business entities are mapped or deprecated",
          "Critical workflows declare owners and success signals",
        ],
      },
      {
        id: "p3-m2",
        label: "Replayable Workflows",
        targetWindow: "Week 14",
        outcome: "Failed jobs and handoffs can be inspected, retried, or replayed with context.",
        dependencies: ["p3-m1"],
        exitCriteria: [
          "Idempotency and retry policies are defined",
          "Dead-letter conditions are visible to operators",
          "At least one critical workflow supports manual intervention",
        ],
      },
    ],
    risks: [
      "Business logic stays trapped inside route handlers",
      "Workflow state transitions remain implicit and non-observable",
    ],
  },
  {
    id: "phase-4",
    label: "Enterprise UX",
    objective: "Unify high-frequency operator, client, reviewer, and product experiences under one enterprise interaction system.",
    duration: "Month 5",
    owners: ["public_funnel", "client_reviewer", "platform_reliability"],
    scope: [
      "Shared enterprise shell patterns",
      "Cross-product navigation and state semantics",
      "Accessible, keyboard-friendly data workflows",
      "Workflow-centric information architecture",
    ],
    milestones: [
      {
        id: "p4-m1",
        label: "Interaction Standard",
        targetWindow: "Week 18",
        outcome: "Tables, statuses, notifications, modals, and audit/history views behave consistently.",
        dependencies: ["p3-m2"],
        exitCriteria: [
          "Shared component conventions are documented",
          "Critical operator pages adopt the same interaction rules",
          "Client and reviewer states are visually distinct but platform-consistent",
        ],
      },
    ],
    risks: [
      "Polish outpaces workflow correctness",
      "Each app preserves its own navigation semantics",
    ],
  },
  {
    id: "phase-5",
    label: "Operational Perfection",
    objective: "Lock reliability, governance, launch gates, and supportability to enterprise standards.",
    duration: "Month 6",
    owners: ["platform_reliability", "identity_access", "workflow_orchestration"],
    scope: [
      "Health, alerting, and release verification",
      "Governance cadence and runbooks",
      "Support/operator intervention tools",
      "Enterprise launch evidence",
    ],
    milestones: [
      {
        id: "p5-m1",
        label: "Reliability Gates",
        targetWindow: "Week 22",
        outcome: "Deploys, route health, workflow health, and dependency readiness have automated checks and documented recovery.",
        dependencies: ["p4-m1"],
        exitCriteria: [
          "Critical route smoke checks are automated",
          "Runbooks exist for known failure classes",
          "Rollback criteria are documented",
        ],
      },
      {
        id: "p5-m2",
        label: "Enterprise Launch Readiness",
        targetWindow: "Week 24",
        outcome: "The platform can demonstrate operational trust, ownership, and recovery procedures.",
        dependencies: ["p5-m1"],
        exitCriteria: [
          "Ownership is explicit for every critical subsystem",
          "Audit, workflow, and health evidence is available",
          "No unresolved Sev-1 blind spots remain",
        ],
      },
    ],
    risks: [
      "Observability is added too late to influence development behavior",
      "Runbooks exist but are not tied to concrete gates and evidence",
    ],
  },
];

const deliveryGates: DeliveryGate[] = [
  {
    id: "gate-architecture",
    label: "Architecture Convergence Gate",
    phaseId: "phase-1",
    category: "architecture",
    requiredEvidence: [
      "Machine-readable manifest route",
      "Canonical env template",
      "Repo docs that declare one source of truth",
    ],
    blockingConditions: [
      "Competing source-of-truth docs remain active",
      "Critical surfaces are missing from manifest",
    ],
    approvers: ["platform-shell-owner", "platform-ops"],
  },
  {
    id: "gate-access",
    label: "Identity And Access Gate",
    phaseId: "phase-2",
    category: "security",
    requiredEvidence: [
      "Shared permission matrix",
      "Audit events on privileged actions",
      "Tenant boundary tests for client and reviewer scopes",
    ],
    blockingConditions: [
      "Protected routes lack explicit permission mapping",
      "Privileged actions are unaudited",
    ],
    approvers: ["platform-admin", "finance-owner"],
  },
  {
    id: "gate-workflow",
    label: "Workflow Observability Gate",
    phaseId: "phase-3",
    category: "workflow",
    requiredEvidence: [
      "Canonical event contract",
      "Retry/replay/dead-letter definitions",
      "Operator visibility into stuck workflows",
    ],
    blockingConditions: [
      "Critical flows still rely on hidden side effects",
      "Failed jobs cannot be diagnosed or replayed",
    ],
    approvers: ["orchestration-owner", "control-plane-owner"],
  },
  {
    id: "gate-ux",
    label: "Enterprise UX Gate",
    phaseId: "phase-4",
    category: "ux",
    requiredEvidence: [
      "Shared interaction conventions",
      "Accessibility checks for key flows",
      "Cross-product navigation coherence",
    ],
    blockingConditions: [
      "Critical operator surfaces still behave inconsistently",
      "Client/reviewer experiences are not accessibility-reviewed",
    ],
    approvers: ["brand-experience-owner", "client-portal-owner"],
  },
  {
    id: "gate-launch",
    label: "Operational Launch Gate",
    phaseId: "phase-5",
    category: "launch",
    requiredEvidence: [
      "Automated smoke checks",
      "Runbooks for known incidents",
      "Ownership and escalation coverage for critical services",
    ],
    blockingConditions: [
      "No rollback criteria",
      "Critical routes lack health or smoke coverage",
    ],
    approvers: ["platform-ops", "platform-owner"],
  },
];

export function getPlatformManifest(): PlatformManifest {
  return {
    id: "contentco-op-platform",
    label: "Content Co-op Unified Platform",
    generatedFor: "phase_1_platform_convergence",
    canonicalRepoRoot: "monorepo",
    version: PLATFORM_VERSION,
    generatedAt: new Date().toISOString(),
    architectureDecision:
      "The monorepo is the canonical implementation home for active public, product, control-plane, and service surfaces.",
    vocabulary: {
      platform_shell: "The primary public and internal entry surface implemented by apps/home.",
      control_plane: "Internal operator surfaces under /root for finance, marketing, system, and intervention workflows.",
      domain_product: "A specialized product workspace such as Co-Cut, Co-Script, or Co-Deliver.",
      client_reviewer_surface: "Any authenticated or tokenized surface intended for clients or external reviewers.",
      platform_service: "A non-primary-UI service or worker that powers orchestration, media, or document generation.",
    },
    surfaces,
    modules,
    runtime,
    dependencies,
    criticalRoutes,
    criticalWorkflows,
    deployment: {
      order: ["home", "orchestrator", "documents", "media-worker", "coscript", "codeliver", "cocut"],
      releaseVerification: [
        "npm run lint",
        "npm run typecheck",
        "npm run build",
        "GET /api/health",
        "GET /api/platform/manifest",
      ],
      smokeRouteIds: ["public-home", "portfolio", "booking", "brief", "health-api", "manifest-api"],
    },
    execution: {
      horizon: "6 months",
      principles: [
        "Platform before polish, but polish in every phase.",
        "No customer-impacting automation without explicit human-safe boundaries.",
        "Every critical subsystem must have an owner, a health signal, and a recovery path.",
        "Docs, runtime behavior, and verification must describe the same platform reality.",
      ],
      phases: executionPhases,
      deliveryGates,
    },
    legacyRepos: [
      {
        label: "Legacy Co-Cut standalone repo",
        path: "../cocut",
        status: "maintenance_only",
        notes: "Do not treat as a primary feature-development target.",
      },
      {
        label: "Legacy Co-Script standalone repo",
        path: "../coscript",
        status: "maintenance_only",
        notes: "Monorepo implementation is the primary source of truth.",
      },
      {
        label: "Legacy Co-Deliver standalone repo",
        path: "../codeliver",
        status: "maintenance_only",
        notes: "Keep only for emergency compatibility until fully retired.",
      },
    ],
  };
}
