type GalleryImage = {
  src: string;
  alt: string;
  label: string;
  tag: string;
};

export const heroClips = [
  "/cc/video/hero-1.mp4",
  "/cc/video/hero-2.mp4",
  "/cc/video/hero-3.mp4",
  "/cc/video/hero-5.mp4",
  "/cc/video/hero-6.mp4",
  "/cc/video/hero-7.mp4",
  "/cc/video/hero-8.mp4",
  "/cc/video/hero-9.mp4",
  "/cc/video/hero-10.mp4",
  "/cc/video/hero-11.mp4",
  "/cc/video/hero-12.mp4",
  "/cc/video/hero-13.mp4",
  "/cc/video/hero-14.mp4",
  "/cc/video/hero-17.mp4",
  "/cc/video/hero-18.mp4",
  "/cc/video/hero-19.mp4",
  "/cc/video/hero-20.mp4",
  "/cc/video/hero-21.mp4",
  "/cc/video/hero-23.mp4",
  "/cc/video/hero-24.mp4",
  "/cc/video/hero-25.mp4",
  "/cc/video/hero-26.mp4",
  "/cc/video/hero-27.mp4",
  "/cc/video/hero-28.mp4",
  "/cc/video/hero-29.mp4",
  "/cc/video/hero-30.mp4",
  "/cc/video/hero-31.mp4",
  "/cc/video/hero-32.mp4",
  "/cc/video/hero-33.mp4",
  "/cc/video/hero-35.mp4",
  "/cc/video/hero-38.mp4",
  "/cc/video/hero-36.mp4",
  "/cc/portfolio-cdn/preview_citgo_ep5.mp4",
  "/cc/portfolio-cdn/preview_citgo_ep9.mp4",
] as const;

export const galleryImages: readonly GalleryImage[] = [
  { src: "/cc/photos/gallery-control-room.jpg", alt: "BP control room operator monitoring screens", label: "Whiting Refinery", tag: "Production" },
  { src: "/cc/photos/gallery-drone-platform.jpg", alt: "DJI Inspire drone on offshore platform", label: "Aerial Unit", tag: "BTS" },
  { src: "/cc/photos/gallery-crew-refinery.jpg", alt: "CC crew prepping gimbal at refinery", label: "BP Whiting", tag: "BTS" },
  { src: "/cc/photos/gallery-crew-field-shoot.jpg", alt: "CC crew shooting in tall grass", label: "Fowler Ridge", tag: "BTS" },
  { src: "/cc/photos/gallery-machinist-cnc.jpg", alt: "Machinist operating CNC mill", label: "Precision MFG", tag: "Industrial" },
  { src: "/cc/photos/gallery-fire-gear-rack.jpg", alt: "Fire gear rack with American flag patch", label: "First Response", tag: "Safety" },
  { src: "/cc/photos/gallery-kodiak-crew.jpg", alt: "Kodiak field crew in hard hats", label: "Permian Basin", tag: "Upstream" },
  { src: "/cc/photos/gallery-lineman-boom.jpg", alt: "Lineman with boom mic reflector", label: "Wind Farm", tag: "Production" },
  { src: "/cc/photos/gallery-campus-sunflare.jpg", alt: "Corporate campus walkway at golden hour", label: "BP Houston", tag: "Corporate" },
  { src: "/cc/photos/gallery-ceraweek-speaker.jpg", alt: "CeraWeek conference speaker", label: "CeraWeek", tag: "Events" },
  { src: "/cc/photos/fowler-wind-turbine.jpg", alt: "Wind turbine blade assembly at Fowler Ridge", label: "Fowler Ridge", tag: "Wind" },
  { src: "/cc/photos/whiting-refinery-sunset.jpg", alt: "Whiting Refinery skyline at golden hour", label: "Whiting Refinery", tag: "Downstream" },
  { src: "/cc/photos/gallery-wind-turbine-crane.jpg", alt: "Wind turbine crane lift at height", label: "Crane Lift", tag: "Wind" },
  { src: "/cc/photos/gallery-refinery-mountains.jpg", alt: "Refinery with snow-capped mountains", label: "Cherry Point", tag: "Downstream" },
  { src: "/cc/photos/gallery-helipad-sunset.jpg", alt: "Offshore helipad at golden hour", label: "Atlantis", tag: "Offshore" },
  { src: "/cc/photos/gallery-aerial-solar.jpg", alt: "Aerial view of solar farm", label: "Solar Array", tag: "Renewables" },
  { src: "/cc/photos/gallery-bp-tower-drone.jpg", alt: "BP tower drone shot at dusk", label: "Houston HQ", tag: "Corporate" },
  { src: "/cc/photos/gallery-desert-tanks.jpg", alt: "Desert storage tanks at golden hour", label: "Permian Basin", tag: "Upstream" },
  { src: "/cc/photos/gallery-refinery-pink-sunset.jpg", alt: "Refinery skyline with pink sunset and steam", label: "Whiting", tag: "Downstream" },
  { src: "/cc/photos/gallery-gas-station-sunset.jpg", alt: "Gas station at sunset", label: "Retail", tag: "Downstream" },
  { src: "/cc/photos/seagull-rope-access.jpg", alt: "Rope access workers on offshore platform", label: "Project Seagull", tag: "Offshore" },
];
