import type { PortfolioCaseStudy } from "@contentco-op/types";

const reviewedAt = "2026-03-17";

export const portfolioExtendedStudies: PortfolioCaseStudy[] = [
  {
    id: "bpms150-drone",
    title: "BP MS150 Finish Line Aerial",
    client: "BP",
    sector: "Events",
    year: "2024",
    format: "Aerial event cut",
    scope: "Drone finish line coverage",
    headline: "Event scale captured from the air, not flattened into recap footage.",
    summary: "A focused aerial cut from BP's MS150 coverage built around finish-line momentum and scale.",
    mandate: "Show the event's emotional peak and physical scale from a premium vantage point.",
    execution: "Drone movement, crowd rhythm, and pace control create a cleaner event proof piece.",
    outcome: "A sharper event story for recap, internal pride, and brand use.",
    proofPoints: ["Drone coverage", "Finish-line energy", "Event scale"],
    deliverables: ["Aerial event film", "Recap asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_bpms150_drone.jpg",
    preview: "/cc/portfolio-cdn/preview_bpms150.mp4",
    video: "/cc/portfolio-cdn/BPMS150_Drone_FinishLine1.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [
      { src: "/cc/portfolio-cdn/thumb_bpms150_drone.jpg", alt: "BP MS150 drone coverage" },
      { src: "/cc/portfolio-cdn/thumb_bpms150_slomo.jpg", alt: "BP MS150 slow-motion finish line" },
    ],
  },
  {
    id: "gno-campaign",
    title: "Pinot's Palette Girls Night Out",
    client: "Pinot's Palette",
    sector: "Experiential franchise marketing",
    year: "2024",
    format: "Reservation-driving campaign film",
    scope: "59-second paint-and-sip campaign cut for Pinot's Palette Girls Night Out, built from studio footage, customer testimonials, group painting moments, reservation prompts, and a nationwide studio CTA",
    headline: "A girls-night-out campaign that sells the room, not just the class.",
    summary:
      "Pinot's Palette's Girls Night Out cut turns a paint-and-sip studio into a social proof asset: wine-glass cheers, group photos, apron-and-canvas instruction, customer callouts, phone-shot UGC texture, reserved-seating graphics, and a national studio CTA all make the experience feel easy to book.",
    mandate: "Show why a private painting night feels low-pressure, social, and repeatable across franchise studios, while keeping the edit fast enough for web and social promotion.",
    execution:
      "Content Co-op paired upbeat studio b-roll with kinetic typography, handwritten testimonial overlays, bold objection-handling graphics, and close-up painting details so the campaign answers common hesitations: no experience required, clear instruction, music, party atmosphere, and enough seats for a group.",
    outcome:
      "The finished 59-second spot gives Pinot's Palette a booking-focused campaign asset for girls-night-out, private-party, franchise, and studio marketing without losing the color and looseness of the actual room.",
    proofPoints: ["Paint-and-sip studio footage", "Girls-night-out reservation prompt", "Customer testimonial overlays", "No-experience-needed messaging", "Nationwide studio CTA"],
    deliverables: ["59-second campaign film", "Private-party promo asset", "Studio marketing cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_gno.jpg",
    preview: "/cc/portfolio-cdn/GNO_03.mp4",
    video: "/cc/portfolio-cdn/GNO_03.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_gno.jpg", alt: "Pinot's Palette Girls Night Out paint-and-sip campaign" }],
  },
  {
    id: "ica-aerial",
    title: "ICA Aerial Proof",
    client: "ICA",
    sector: "Executive",
    year: "2024",
    format: "Aerial brand cut",
    scope: "Site overview and positioning",
    headline: "Aerial coverage used as proof, not wallpaper.",
    summary: "A concise aerial-driven piece built to show site scale and executive-facing visual confidence.",
    mandate: "Make the environment readable from above without losing commercial polish.",
    execution: "Aerial motion and selective edit density keep the piece elevated and legible.",
    outcome: "A cleaner site-overview asset for brand, sales, and executive contexts.",
    proofPoints: ["Aerial proof", "Site scale", "Executive polish"],
    deliverables: ["Aerial film", "Executive-facing brand asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_ica_aerial.jpg",
    preview: "/cc/portfolio-cdn/preview_ica_aerial.mp4",
    video: "/cc/portfolio-cdn/preview_ica_aerial.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_ica_aerial.jpg", alt: "ICA aerial" }],
  },
  {
    id: "ica-ceo",
    title: "ICA Executive Story",
    client: "ICA",
    sector: "Executive",
    year: "2024",
    format: "Executive profile",
    scope: "CEO-led proof piece",
    headline: "Executive messaging framed with enough restraint to feel credible.",
    summary: "A leadership-facing cut built around presence, confidence, and tighter framing.",
    mandate: "Let the executive voice carry authority without turning the cut into empty corporate theater.",
    execution: "Direct interview framing and controlled supporting imagery shape the piece.",
    outcome: "A more credible executive brand asset for leadership and external audiences.",
    proofPoints: ["Executive presence", "Interview-first", "Credible polish"],
    deliverables: ["Executive profile film", "Leadership clip"],
    thumbnail: "/cc/portfolio-cdn/thumb_ica_ceo.jpg",
    preview: "/cc/portfolio-cdn/preview_ica_ceo.mp4",
    video: "/cc/portfolio-cdn/preview_ica_ceo.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_ica_ceo.jpg", alt: "ICA executive profile" }],
  },
  {
    id: "pinots-palettes",
    title: "Pinot's Palette",
    client: "Pinot's Palette",
    sector: "Retail brand",
    year: "2024",
    format: "Brand spot",
    scope: "Experience-led promo",
    headline: "An experience brand cut with stronger visual rhythm than standard local promo work.",
    summary: "A colorful promo piece built around environment, customer energy, and clean short-form pacing.",
    mandate: "Make the space feel alive without losing commercial clarity.",
    execution: "Punchier edit rhythm and brighter visual beats keep the experience readable and premium.",
    outcome: "A retail-facing brand asset that feels energetic instead of generic.",
    proofPoints: ["Experience-led", "Short-form rhythm", "Retail clarity"],
    deliverables: ["Brand promo", "Experience cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_pinots.jpg",
    preview: "/cc/portfolio-cdn/preview_pinots.mp4",
    video: "/cc/portfolio-cdn/preview_pinots.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_pinots.jpg", alt: "Pinot's Palette" }],
  },
  {
    id: "title-promo",
    title: "Title Promo",
    client: "Live Venue Promo",
    sector: "Campaign",
    year: "2024",
    format: "Promo spot",
    scope: "Motion-led title sequence",
    headline: "A promo cut where typography and editorial timing carry the energy.",
    summary: "A title-driven promotional asset built to feel immediate, bright, and event-ready.",
    mandate: "Let motion language and timing do the persuasion fast.",
    execution: "Quick transitions, punchy beats, and title-first framing create a cleaner promo asset.",
    outcome: "A sharper promo cut for event and hype contexts.",
    proofPoints: ["Title-first motion", "Promo energy", "Fast editorial"],
    deliverables: ["Promo spot", "Event opener asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_title_promo.jpg",
    preview: "/cc/portfolio-cdn/The_Title_Promo_X_2.mp4",
    video: "/cc/portfolio-cdn/The_Title_Promo_X_2.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_title_promo.jpg", alt: "Title promo" }],
  },
  {
    id: "jumbotron",
    title: "Jumbotron Promo",
    client: "Live Events",
    sector: "Campaign",
    year: "2024",
    format: "Venue spot",
    scope: "Large-format event screen promo",
    headline: "A large-format promo cut designed to hit fast in a live environment.",
    summary: "Built for venue screens and immediate audience read, this piece leans into scale and timing.",
    mandate: "Make every second read quickly on a giant screen in a noisy environment.",
    execution: "Fast visual beats, oversized framing, and direct motion cues support the format.",
    outcome: "A venue-ready promo that feels big enough for the screen it was built for.",
    proofPoints: ["Large-screen clarity", "Live environment", "Fast reads"],
    deliverables: ["Jumbotron promo", "Venue spot"],
    thumbnail: "/cc/portfolio-cdn/thumb_jumbotron.jpg",
    preview: "/cc/portfolio-cdn/XXX_Final_Jumbotron.mp4",
    video: "/cc/portfolio-cdn/XXX_Final_Jumbotron.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_jumbotron.jpg", alt: "Jumbotron promo" }],
  },
  {
    id: "bp-stem",
    title: "BP STEM Story",
    client: "BP",
    sector: "Education",
    year: "2024",
    format: "Community brand cut",
    scope: "STEM program coverage",
    headline: "Community-facing BP storytelling with more polish than standard CSR recap.",
    summary: "A STEM-oriented piece built to connect brand presence with education and future workforce messaging.",
    mandate: "Make the program feel tangible and credible, not abstract or overly sentimental.",
    execution: "Clean event framing and selective emotional beats keep the cut grounded.",
    outcome: "A stronger proof asset for education, community, and brand narratives.",
    proofPoints: ["Community proof", "Program visibility", "Brand restraint"],
    deliverables: ["Program story", "Community brand asset"],
    thumbnail: "/cc/photos/gallery-bp-stem-swimming.jpg",
    preview: "/cc/portfolio-cdn/preview_bp_stem.mp4",
    video: "/cc/portfolio-cdn/preview_bp_stem.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/photos/gallery-bp-stem-swimming.jpg", alt: "BP STEM swimming story" }],
  },
];
