import type { PortfolioCaseStudy } from "@contentco-op/types";

const reviewedAt = "2026-03-17";

export const portfolioExtendedStudies: PortfolioCaseStudy[] = [
  {
    id: "citgo-lcr-ep2",
    title: "Life Critical Rules — Episode 2",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 2 of 9",
    headline: "Training proof shaped for repeat field viewing.",
    summary: "A single episode from the LCR system, built to be usable on its own without losing rollout consistency.",
    mandate: "Make one rule immediately understandable for crews while keeping the series language disciplined.",
    execution: "Episode pacing, bold visual hierarchy, and direct instruction work together as a standalone safety asset.",
    outcome: "A modular training cut that still feels part of a serious system.",
    proofPoints: ["Episode architecture", "Crew readability", "Series consistency"],
    deliverables: ["Standalone episode", "Training rollout asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep2.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep2.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep2_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep2.jpg", alt: "CITGO LCR Episode 2" }],
  },
  {
    id: "citgo-lcr-ep3",
    title: "Life Critical Rules — Episode 3",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 3 of 9",
    headline: "Operational safety packaged with episode-level clarity.",
    summary: "A focused episode cut for rule-specific communication inside a larger training system.",
    mandate: "Hold the seriousness of the subject while keeping the viewing experience clean and repeatable.",
    execution: "Live footage, motion framing, and modular structure keep the message direct.",
    outcome: "High-clarity safety media that can slot into real operations training.",
    proofPoints: ["Rule-specific clarity", "Repeatable packaging", "Operations-safe tone"],
    deliverables: ["Standalone episode", "Safety rollout asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep3.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep3.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep3_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep3.jpg", alt: "CITGO LCR Episode 3" }],
  },
  {
    id: "citgo-lcr-ep4",
    title: "Life Critical Rules — Episode 4",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 4 of 9",
    headline: "Safety instruction that reads as a system, not a slide deck.",
    summary: "An episodic training unit tuned for comprehension, repetition, and rollout discipline.",
    mandate: "Prevent the message from feeling generic while keeping it structured enough for reuse.",
    execution: "Each beat is trimmed for comprehension speed and consistency with the broader series.",
    outcome: "An episode that feels reusable and serious inside operational review.",
    proofPoints: ["System thinking", "Reusable training", "Operational cadence"],
    deliverables: ["Episode asset", "Training media"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep4.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep4.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep4_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep4.jpg", alt: "CITGO LCR Episode 4" }],
  },
  {
    id: "citgo-lcr-ep5",
    title: "Life Critical Rules — Episode 5",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 5 of 9",
    headline: "A rollout-ready training cut with high replay value.",
    summary: "This episode balances explanation, motion, and credibility for repeated internal use.",
    mandate: "Keep the message watchable enough to survive repetition without softening the instruction.",
    execution: "Structured visual rhythm and restrained editing keep the rule legible.",
    outcome: "A durable episode for field communication and training review.",
    proofPoints: ["Replay value", "Instructional pacing", "Series discipline"],
    deliverables: ["Episode asset", "Internal training media"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep5.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep5.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep5_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep5.jpg", alt: "CITGO LCR Episode 5" }],
  },
  {
    id: "citgo-lcr-ep6",
    title: "Life Critical Rules — Episode 6",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 6 of 9",
    headline: "Direct rule communication built to hold up under HSE review.",
    summary: "A single-episode safety asset that stays credible to both crews and compliance-minded reviewers.",
    mandate: "Make the message usable in the field without losing review-room seriousness.",
    execution: "Disciplined structure and proof-led framing keep the piece aligned with real rollout needs.",
    outcome: "A rule-specific episode that remains clean, credible, and reusable.",
    proofPoints: ["HSE credibility", "Field usability", "Rule-specific framing"],
    deliverables: ["Episode asset", "Safety communications cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep6.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep6.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep6_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep6.jpg", alt: "CITGO LCR Episode 6" }],
  },
  {
    id: "citgo-lcr-ep7",
    title: "Life Critical Rules — Episode 7",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 7 of 9",
    headline: "Modular training media with rollout-level consistency.",
    summary: "An additional series episode presented as a standalone training proof point.",
    mandate: "Show that the system scales episode by episode without quality drift.",
    execution: "Visual continuity, controlled pacing, and clear instruction keep the format stable.",
    outcome: "A repeatable episode package that strengthens the overall training system story.",
    proofPoints: ["Scalable format", "Episode continuity", "Operational consistency"],
    deliverables: ["Standalone episode", "Series proof asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep7.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep7.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep7_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep7.jpg", alt: "CITGO LCR Episode 7" }],
  },
  {
    id: "citgo-lcr-ep8",
    title: "Life Critical Rules — Episode 8",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 8 of 9",
    headline: "An instructional episode that stays sharp across repeat use.",
    summary: "One rule-focused episode from the broader CITGO training set, tuned for clarity and retention.",
    mandate: "Preserve viewer attention without reducing the seriousness of the instruction.",
    execution: "A clean narrative spine and restrained motion keep the episode readable under repetition.",
    outcome: "A durable training piece that still feels premium enough to trust.",
    proofPoints: ["Retention-focused", "Readable pacing", "Premium training feel"],
    deliverables: ["Episode asset", "Rule-specific training media"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep8.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep8.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep8_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep8.jpg", alt: "CITGO LCR Episode 8" }],
  },
  {
    id: "citgo-lcr-ep9",
    title: "Life Critical Rules — Episode 9",
    client: "CITGO Petroleum",
    sector: "Safety systems",
    year: "2024",
    format: "Safety series episode",
    scope: "Episode 9 of 9",
    headline: "Series-end proof from a disciplined training rollout.",
    summary: "A final episode view into the broader CITGO LCR production system and its repeatable design language.",
    mandate: "Show finishing consistency across the entire training sequence.",
    execution: "The episode closes the series with the same visual discipline and rollout logic as the rest.",
    outcome: "A strong endpoint for the full series and another standalone proof asset.",
    proofPoints: ["Series finish", "Rollout proof", "Consistent packaging"],
    deliverables: ["Episode asset", "Series capstone cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_citgo_ep9.jpg",
    preview: "/cc/portfolio-cdn/preview_citgo_ep9.mp4",
    video: "/cc/portfolio-cdn/CITGO_LCR_Ep9_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_citgo_ep9.jpg", alt: "CITGO LCR Episode 9" }],
  },
  {
    id: "bpms150-drone",
    title: "BP MS150 Finish Line Aerial",
    client: "BP",
    sector: "Events",
    year: "2024",
    format: "Aerial event cut",
    scope: "Drone finish line coverage",
    headline: "Event scale captured from the air, not flattened into recap footage.",
    summary: "A focused aerial cut from BP's MS150 coverage built around finish-line momentum and scale.",
    mandate: "Show the event's emotional peak and physical scale from a premium vantage point.",
    execution: "Drone movement, crowd rhythm, and pace control create a cleaner event proof piece.",
    outcome: "A sharper event story for recap, internal pride, and brand use.",
    proofPoints: ["Drone coverage", "Finish-line energy", "Event scale"],
    deliverables: ["Aerial event film", "Recap asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_bpms150_drone.jpg",
    preview: "/cc/portfolio-cdn/preview_bpms150.mp4",
    video: "/cc/portfolio-cdn/BPMS150_Drone_FinishLine1.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [
      { src: "/cc/portfolio-cdn/thumb_bpms150_drone.jpg", alt: "BP MS150 drone coverage" },
      { src: "/cc/portfolio-cdn/thumb_bpms150_slomo.jpg", alt: "BP MS150 slow-motion finish line" },
    ],
  },
  {
    id: "bp-rodeo-recap",
    title: "BP Rodeo Recap",
    client: "BP",
    sector: "Events",
    year: "2024",
    format: "Event recap",
    scope: "Rodeo coverage and crowd energy",
    headline: "Brand-event coverage with enough pace to feel current and enough discipline to stay useful.",
    summary: "A recap cut built around atmosphere, audience energy, and clean brand presentation.",
    mandate: "Turn rodeo access into something more durable than a social dump.",
    execution: "Fast event rhythm, controlled transitions, and sharp highlight selection.",
    outcome: "A premium brand-event recap that still feels grounded in the live experience.",
    proofPoints: ["Event rhythm", "Audience energy", "Brand-safe recap"],
    deliverables: ["Event recap film", "Brand highlight cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_rodeo_recap.jpg",
    preview: "/cc/portfolio-cdn/Rodeo_Recap_BP_web.mp4",
    video: "/cc/portfolio-cdn/Rodeo_Recap_BP_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_rodeo_recap.jpg", alt: "BP Rodeo Recap" }],
  },
  {
    id: "gno-campaign",
    title: "GNO Campaign Cut",
    client: "GNO",
    sector: "Campaign",
    year: "2024",
    format: "Campaign film",
    scope: "Short-form brand campaign",
    headline: "A compact campaign cut built to move with speed, not feel disposable.",
    summary: "A shorter campaign asset where timing, transitions, and visual punch do the heavy lifting.",
    mandate: "Keep the piece energetic without sacrificing polish.",
    execution: "Short-form pacing and punchier editorial choices keep the cut alive.",
    outcome: "A campaign asset that feels fast, sharp, and reusable.",
    proofPoints: ["Campaign velocity", "Tight editorial", "Short-form polish"],
    deliverables: ["Campaign film", "Short-form promo"],
    thumbnail: "/cc/portfolio-cdn/thumb_gno.jpg",
    preview: "/cc/portfolio-cdn/GNO_03.mp4",
    video: "/cc/portfolio-cdn/GNO_03.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_gno.jpg", alt: "GNO campaign" }],
  },
  {
    id: "hlsr-2024",
    title: "Houston Livestock Show 2024",
    client: "HLSR",
    sector: "Events",
    year: "2024",
    format: "Event film",
    scope: "Show-floor and crowd coverage",
    headline: "A large-format event recap with premium pacing and real crowd scale.",
    summary: "Coverage from the 2024 Houston Livestock Show shaped into a clean, high-energy recap.",
    mandate: "Capture the event's scale without letting the footage collapse into visual noise.",
    execution: "Wide coverage, selective hero moments, and sharper editorial control.",
    outcome: "An event asset that feels polished enough for sponsors, teams, and future promotion.",
    proofPoints: ["Crowd scale", "Event energy", "Sponsor-ready"],
    deliverables: ["Event recap film", "Promotional recap asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_hlsr_2024.jpg",
    preview: "/cc/portfolio-cdn/HLSR_2024_web.mp4",
    video: "/cc/portfolio-cdn/HLSR_2024_web.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_hlsr_2024.jpg", alt: "Houston Livestock Show 2024" }],
  },
  {
    id: "ica-aerial",
    title: "ICA Aerial Proof",
    client: "ICA",
    sector: "Executive",
    year: "2024",
    format: "Aerial brand cut",
    scope: "Site overview and positioning",
    headline: "Aerial coverage used as proof, not wallpaper.",
    summary: "A concise aerial-driven piece built to show site scale and executive-facing visual confidence.",
    mandate: "Make the environment readable from above without losing commercial polish.",
    execution: "Aerial motion and selective edit density keep the piece elevated and legible.",
    outcome: "A cleaner site-overview asset for brand, sales, and executive contexts.",
    proofPoints: ["Aerial proof", "Site scale", "Executive polish"],
    deliverables: ["Aerial film", "Executive-facing brand asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_ica_aerial.jpg",
    preview: "/cc/portfolio-cdn/preview_ica_aerial.mp4",
    video: "/cc/portfolio-cdn/preview_ica_aerial.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_ica_aerial.jpg", alt: "ICA aerial" }],
  },
  {
    id: "ica-ceo",
    title: "ICA Executive Story",
    client: "ICA",
    sector: "Executive",
    year: "2024",
    format: "Executive profile",
    scope: "CEO-led proof piece",
    headline: "Executive messaging framed with enough restraint to feel credible.",
    summary: "A leadership-facing cut built around presence, confidence, and tighter framing.",
    mandate: "Let the executive voice carry authority without turning the cut into empty corporate theater.",
    execution: "Direct interview framing and controlled supporting imagery shape the piece.",
    outcome: "A more credible executive brand asset for leadership and external audiences.",
    proofPoints: ["Executive presence", "Interview-first", "Credible polish"],
    deliverables: ["Executive profile film", "Leadership clip"],
    thumbnail: "/cc/portfolio-cdn/thumb_ica_ceo.jpg",
    preview: "/cc/portfolio-cdn/preview_ica_ceo.mp4",
    video: "/cc/portfolio-cdn/preview_ica_ceo.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_ica_ceo.jpg", alt: "ICA executive profile" }],
  },
  {
    id: "pinots-palettes",
    title: "Pinot's Palette",
    client: "Pinot's Palette",
    sector: "Retail brand",
    year: "2024",
    format: "Brand spot",
    scope: "Experience-led promo",
    headline: "An experience brand cut with stronger visual rhythm than standard local promo work.",
    summary: "A colorful promo piece built around environment, customer energy, and clean short-form pacing.",
    mandate: "Make the space feel alive without losing commercial clarity.",
    execution: "Punchier edit rhythm and brighter visual beats keep the experience readable and premium.",
    outcome: "A retail-facing brand asset that feels energetic instead of generic.",
    proofPoints: ["Experience-led", "Short-form rhythm", "Retail clarity"],
    deliverables: ["Brand promo", "Experience cut"],
    thumbnail: "/cc/portfolio-cdn/thumb_pinots.jpg",
    preview: "/cc/portfolio-cdn/preview_pinots.mp4",
    video: "/cc/portfolio-cdn/preview_pinots.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_pinots.jpg", alt: "Pinot's Palette" }],
  },
  {
    id: "title-promo",
    title: "Title Promo",
    client: "Live Venue Promo",
    sector: "Campaign",
    year: "2024",
    format: "Promo spot",
    scope: "Motion-led title sequence",
    headline: "A promo cut where typography and editorial timing carry the energy.",
    summary: "A title-driven promotional asset built to feel immediate, bright, and event-ready.",
    mandate: "Let motion language and timing do the persuasion fast.",
    execution: "Quick transitions, punchy beats, and title-first framing create a cleaner promo asset.",
    outcome: "A sharper promo cut for event and hype contexts.",
    proofPoints: ["Title-first motion", "Promo energy", "Fast editorial"],
    deliverables: ["Promo spot", "Event opener asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_title_promo.jpg",
    preview: "/cc/portfolio-cdn/The_Title_Promo_X_2.mp4",
    video: "/cc/portfolio-cdn/The_Title_Promo_X_2.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_title_promo.jpg", alt: "Title promo" }],
  },
  {
    id: "jumbotron",
    title: "Jumbotron Promo",
    client: "Live Events",
    sector: "Campaign",
    year: "2024",
    format: "Venue spot",
    scope: "Large-format event screen promo",
    headline: "A large-format promo cut designed to hit fast in a live environment.",
    summary: "Built for venue screens and immediate audience read, this piece leans into scale and timing.",
    mandate: "Make every second read quickly on a giant screen in a noisy environment.",
    execution: "Fast visual beats, oversized framing, and direct motion cues support the format.",
    outcome: "A venue-ready promo that feels big enough for the screen it was built for.",
    proofPoints: ["Large-screen clarity", "Live environment", "Fast reads"],
    deliverables: ["Jumbotron promo", "Venue spot"],
    thumbnail: "/cc/portfolio-cdn/thumb_jumbotron.jpg",
    preview: "/cc/portfolio-cdn/XXX_Final_Jumbotron.mp4",
    video: "/cc/portfolio-cdn/XXX_Final_Jumbotron.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_jumbotron.jpg", alt: "Jumbotron promo" }],
  },
  {
    id: "bp-stem",
    title: "BP STEM Story",
    client: "BP",
    sector: "Education",
    year: "2024",
    format: "Community brand cut",
    scope: "STEM program coverage",
    headline: "Community-facing BP storytelling with more polish than standard CSR recap.",
    summary: "A STEM-oriented piece built to connect brand presence with education and future workforce messaging.",
    mandate: "Make the program feel tangible and credible, not abstract or overly sentimental.",
    execution: "Clean event framing and selective emotional beats keep the cut grounded.",
    outcome: "A stronger proof asset for education, community, and brand narratives.",
    proofPoints: ["Community proof", "Program visibility", "Brand restraint"],
    deliverables: ["Program story", "Community brand asset"],
    thumbnail: "/cc/portfolio-cdn/thumb_bp_stem.jpg",
    preview: "/cc/portfolio-cdn/preview_bp_stem.mp4",
    video: "/cc/portfolio-cdn/preview_bp_stem.mp4",
    review: { status: "approved", reviewedBy: "Codex", reviewedAt },
    gallery: [{ src: "/cc/portfolio-cdn/thumb_bp_stem.jpg", alt: "BP STEM story" }],
  },
];
